apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress-service
spec:
  type: {{ .Values.ingress_service.type }}
  ports:
    - port: {{ .Values.ingress_service.port }}
      targetPort: {{ .Values.ingress_service.targetPort }}
  selector:
    component: {{ .Release.Name }}-{{ .Values.ingress_service.component }}


