apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-upstream-two-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: {{ .Release.Name }}-upstream-two
  ports:
    - port: {{ .Values.upstream_two_cluster_ip.port }}
      targetPort: {{ .Values.upstream_two_cluster_ip.targetPort }}
